export const tokenList = [
  {
    id: '1',
    icon: '',
    ticker: 'SOL',
    description: 'Wrapped SOL',
  },
  {
    id: '2',
    icon: '',
    ticker: 'USDC',
    description: 'USD Coin',
  },
  {
    id: '3',
    icon: '',
    ticker: 'USDT',
    description: 'USDT',
  },
  {
    id: '4',
    icon: '',
    ticker: 'SRM',
    description: 'Serum',
  },
  {
    id: '5',
    icon: '',
    ticker: 'BTC',
    description: 'Wrapped Bitcoin(Sollet)',
  },
  {
    id: '6',
    icon: '',
    ticker: 'FIDA',
    description: 'Bonfida',
  },
  {
    id: '6',
    icon: '',
    ticker: 'MER',
    description: 'Mercurial',
  },
  {
    id: '7',
    icon: '',
    ticker: 'CYS',
    description: 'Cykura',
  },
  {
    id: '8',
    icon: '',
    ticker: 'MNGO',
    description: 'Mango',
  },
  {
    id: '9',
    icon: '',
    ticker: 'FTT',
    description: 'FTX Token (Portal)',
  },
  {
    id: '10',
    icon: '',
    ticker: 'SXP',
    description: 'Swipe (Portal)',
  },
  {
    id: '11',
    icon: '',
    ticker: 'UNI',
    description: 'Uniswap (Portal)',
  },
  {
    id: '12',
    icon: '',
    ticker: 'AVAX',
    description: 'AVAX (Portal)',
  },
  {
    id: '13',
    icon: '',
    ticker: 'SNY',
    description: 'Synthetify',
  },
]